"use client";

import { useMemo, useState } from "react";
import { DECADES, PERFECT_PLAYERS, type Decade, type PerfectPlayer } from "./perfect-data";

type Mode="classic"|"iq";
type View="home"|"draft"|"result";
const TEAM_IDS:Record<string,number>={ATL:1610612737,BOS:1610612738,CLE:1610612739,NOP:1610612740,CHI:1610612741,DAL:1610612742,DEN:1610612743,GSW:1610612744,HOU:1610612745,LAC:1610612746,LAL:1610612747,MIA:1610612748,MIL:1610612749,MIN:1610612750,NYK:1610612752,ORL:1610612753,PHI:1610612755,PHX:1610612756,POR:1610612757,SAC:1610612758,SAS:1610612759,OKC:1610612760,TOR:1610612761,UTA:1610612762,WAS:1610612764,DET:1610612765};
const TEAM_NAMES:Record<string,string>={ATL:"老鷹",BOS:"塞爾提克",CLE:"騎士",NOP:"鵜鶘",CHI:"公牛",DAL:"獨行俠",DEN:"金塊",GSW:"勇士",HOU:"火箭",LAC:"快艇",LAL:"湖人",MIA:"熱火",MIL:"公鹿",MIN:"灰狼",NYK:"尼克",ORL:"魔術",PHI:"76人",PHX:"太陽",POR:"拓荒者",SAC:"國王",SAS:"馬刺",OKC:"雷霆",TOR:"暴龍",UTA:"爵士",WAS:"巫師",DET:"活塞"};
const statKeys=["PTS","REB","AST","STL","BLK"] as const;
const shuffle=<T,>(items:T[])=>[...items].sort(()=>Math.random()-.5);
const teamLogo=(team:string)=>TEAM_IDS[team]?`https://cdn.nba.com/logos/nba/${TEAM_IDS[team]}/primary/L/logo.svg`:"";

function candidatesFor(decade:Decade,exclude:string[]=[]){const pool=PERFECT_PLAYERS.filter(p=>p.decade===decade&&!exclude.includes(`${p.name}-${p.decade}`));return shuffle(pool).slice(0,3);}
function totals(roster:PerfectPlayer[]){return {pts:roster.reduce((s,p)=>s+p.pts,0),reb:roster.reduce((s,p)=>s+p.reb,0),ast:roster.reduce((s,p)=>s+p.ast,0),stl:roster.reduce((s,p)=>s+p.stl,0),blk:roster.reduce((s,p)=>s+p.blk,0)};}
function projectWins(roster:PerfectPlayer[]){const t=totals(roster);const clamp=(n:number)=>Math.max(0,Math.min(100,n));const ratings=[clamp((t.pts-105)/.58),clamp((t.reb-34)/.39),clamp((t.ast-18)/.32),clamp((t.stl-3)/.065),clamp((t.blk-2)/.105)];const average=ratings.reduce((a,b)=>a+b,0)/5;const balance=Math.min(...ratings);const strength=average*.68+balance*.32;return {wins:strength>=96&&balance>=90?82:Math.max(28,Math.min(81,Math.round(30+51*Math.pow(strength/100,1.65)))),ratings:ratings.map(Math.round),strength:Math.round(strength),totals:t};}

export default function Perfect82({onExit}:{onExit:()=>void}){
  const [view,setView]=useState<View>("home");const [mode,setMode]=useState<Mode>("classic");const [roster,setRoster]=useState<PerfectPlayer[]>([]);const [decade,setDecade]=useState<Decade>("1990s");const [candidates,setCandidates]=useState<PerfectPlayer[]>([]);const [teamSkip,setTeamSkip]=useState(true);const [decadeSkip,setDecadeSkip]=useState(true);
  const result=useMemo(()=>projectWins(roster),[roster]);
  const beginRound=(nextRoster:PerfectPlayer[],forced?:Decade)=>{const used=new Set(nextRoster.map(p=>p.decade));const open=DECADES.filter(d=>!used.has(d));const next=forced||shuffle(open)[0];setDecade(next);setCandidates(candidatesFor(next,nextRoster.map(p=>`${p.name}-${p.decade}`)));};
  const start=(chosen:Mode)=>{setMode(chosen);setRoster([]);setTeamSkip(true);setDecadeSkip(true);setView("draft");beginRound([]);};
  const pick=(player:PerfectPlayer)=>{const next=[...roster,player];setRoster(next);if(next.length===5)setView("result");else beginRound(next);};
  const skipTeam=()=>{if(!teamSkip)return;setCandidates(candidatesFor(decade,candidates.map(p=>`${p.name}-${p.decade}`)));setTeamSkip(false);};
  const skipDecade=()=>{if(!decadeSkip)return;const used=new Set(roster.map(p=>p.decade));const open=DECADES.filter(d=>!used.has(d)&&d!==decade);beginRound(roster,shuffle(open)[0]);setDecadeSkip(false);};
  const reset=()=>{setView("home");setRoster([]);setCandidates([]);};
  return <main className="app-shell perfect-game">
    <header className="topbar"><button className="wordmark perfect-wordmark" onClick={reset}>PERFECT <i>82</i></button><div className="top-actions"><button className="hub-button" onClick={onExit} aria-label="回到遊戲大廳">⌂</button>{view!=="home"&&<button className="icon-button" onClick={()=>start(mode)} aria-label="重新開始">↻</button>}</div></header>
    {view==="home"&&<section className="perfect-home screen-enter"><div className="eyebrow">ALL-TIME ROSTER CHALLENGE</div><h1>你的夢幻隊<br/>能夠 <em>82–0</em> 嗎？</h1><p className="lead">每輪抽出一個年代，從三位傳奇中選一人。完成五人名單後，模擬整個82場賽季。</p><div className="perfect-hero"><div className="record-zero"><b>82</b><span>–0</span></div><div className="perfect-court"><i/><i/><i/></div><small>THE PERFECT SEASON</small></div><div className="mode-stack"><button onClick={()=>start("classic")}><span>數據模式</span><b>CLASSIC</b><i>完整顯示球員五項巔峰數據 →</i></button><button onClick={()=>start("iq")}><span>記憶模式</span><b>HOOP IQ</b><i>選人時隱藏數據，考驗你的籃球知識 →</i></button></div><div className="rules-mini"><span>5 位傳奇</span><span>7 個年代</span><span>82 場模擬</span></div></section>}
    {view==="draft"&&<section className="perfect-draft screen-enter"><div className="draft-progress"><span>ROSTER {roster.length}/5</span><div>{[0,1,2,3,4].map(i=><i key={i} className={i<roster.length?"filled":i===roster.length?"current":""}/>)}</div></div><div className="era-banner"><div><small>ROUND {roster.length+1}</small><b>{decade}</b><span>從這個年代選出一位傳奇</span></div><strong>{mode==="classic"?"數據公開":"數據隱藏"}</strong></div><div className="perfect-candidates">{candidates.map(player=><button key={`${player.name}-${player.decade}`} onClick={()=>pick(player)}><img src={teamLogo(player.team)} alt={`${TEAM_NAMES[player.team]}標誌`}/><div className="candidate-name"><small>{TEAM_NAMES[player.team]} · {player.pos}</small><b>{player.cname}</b><span>{player.name}</span></div>{mode==="classic"?<div className="candidate-stats">{statKeys.map(key=><div key={key}><b>{player[key.toLowerCase() as "pts"].toFixed(1)}</b><span>{key}</span></div>)}</div>:<div className="stats-hidden"><span>?</span><b>數據將在選擇後揭曉</b></div>}<strong className="pick-player">選擇球員 →</strong></button>)}</div><div className="skip-actions"><button onClick={skipTeam} disabled={!teamSkip}><b>換候選球員</b><span>{teamSkip?"剩餘 1 次":"已使用"}</span></button><button onClick={skipDecade} disabled={!decadeSkip}><b>換年代</b><span>{decadeSkip?"剩餘 1 次":"已使用"}</span></button></div>{roster.length>0&&<div className="drafted-strip">{roster.map(p=><div key={`${p.name}-${p.decade}`}><img src={teamLogo(p.team)} alt=""/><span>{p.cname}</span><b>{p.decade}</b></div>)}</div>}</section>}
    {view==="result"&&<section className="perfect-result screen-enter"><div className="eyebrow">SEASON SIMULATION COMPLETE</div><div className={result.wins===82?"season-record perfect":"season-record"}><small>FINAL RECORD</small><div><b>{result.wins}</b><span>–{82-result.wins}</span></div><strong>{result.wins===82?"PERFECT SEASON":"挑戰完成"}</strong></div><div className="strength-row"><div><span>球隊強度</span><b>{result.strength}</b></div>{statKeys.map((k,i)=><div key={k}><span>{k} 評分</span><b>{result.ratings[i]}</b></div>)}</div><div className="team-totals">{statKeys.map(k=><div key={k}><b>{result.totals[k.toLowerCase() as "pts"].toFixed(1)}</b><span>{k} 總和</span></div>)}</div><div className="final-roster">{roster.map(p=><div key={`${p.name}-${p.decade}`}><img src={teamLogo(p.team)} alt=""/><div><b>{p.cname}</b><span>{p.decade} · {TEAM_NAMES[p.team]} · {p.pos}</span></div><strong>{p.pts.toFixed(1)} PTS · {p.reb.toFixed(1)} REB · {p.ast.toFixed(1)} AST · {p.stl.toFixed(1)} STL · {p.blk.toFixed(1)} BLK</strong></div>)}</div><div className="result-actions"><button className="primary-button" onClick={()=>start(mode)}><span>再挑戰一次</span><b>↻</b></button><button className="secondary-button wide" onClick={onExit}>回到遊戲大廳</button></div></section>}
  </main>;
}
